### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by flaminbabyyoda** [Lenn106/Flocabulary-Hacks#1]
every time i click them it says page not avilable

**Comment by Lenn106** [comment]
I'm sorry, but the reason that doesn't work is because the bookmarklet is still in development. There is no easy way to make hacks for Flocabulary, and the process for it, which I know, is very difficult. I would do this if I was getting paid, but for now, I don't have time. I suggest using Chat GPT to answer your questions on Flocabulary in the meantime. If you want me to make a bookmarklet for that interacts with the Chat GPT api, I will do so. But, keep in mind Chat GPT has a 95% accuracy rate for Flocabulary. This would mean a 100% is not guaranteed. Unlike I-Ready, Flocabulary actually has a decent security system for these sorts of things. I hope you understand.
